name: build wheel for release

on:
  release:
    types: [published]

permissions:
  contents: write # upload artifacts requires this permission

jobs:
  build_wheel:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup python environment
        uses: actions/setup-python@v5

      - name: Build wheel
        run: |
          python3 -m pip install -q -U pip
          pip install -q -U hatch
          hatch build -t wheel

      - name: Upload built wheel as release asset
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.whl
